### ISSUE TITLE
segfault in ssl.c:560

### ISSUE THREAD

**Issue by rubinlinux** [evilnet/nefarious2#75]
When trying to bring up nefarious as a part of a complex matrix bridge webirc setup, I encountered a reproducable segfault (see backtrace below)

I'm guessing that 'forcing' a client's ssl flag true with webirc invalidates some assumptions in other code. In this case, in ssl.c line 560, ssl is null but SSL_get_version() attempts to run on it. The whole block is wrapped in an IsSSL() call, but since we forced that on with webirc, it assumes .ssl is non-null

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f0fb80 in SSL_get_version () from /lib/x86_64-linux-gnu/libssl.so.3
(gdb) bt full
#0  0x00007ffff7f0fb80 in SSL_get_version () from /lib/x86_64-linux-gnu/libssl.so.3
No symbol table info available.
#1  0x00005555556130fc in ssl_get_cipher (ssl=0x0) at ssl.c:560
        buf = '\000' <repeats 399 times>
        bits = 21845
        c = <optimized out>
#2  0x000055555560baa7 in register_user (cptr=0x55555660b240, sptr=0x55555660b240) at s_user.c:455
        parv = {0x55555660b2ce "MatrixBot-b", 0x0, 0x0, 0x3670690366016501 <error: Cannot access memory at address 0x3670690366016501>}
        tmpstr = <optimized out>
        join = {0x7fffffffe5c0 "", 0x5555555c3c48 <doprintf+4952> "H\213\254$\230", 
          0x18381eabc <error: Cannot access memory at address 0x18381eabc>}
        chan = "NOTICE * :*** Checking your client version (sorry..)\r\n", '\000' <repeats 144 times>
        connclass = 0x0
        cliconf = 0x0
        user = 0x555556932810
        ip_base64 = "\0010\0010\0010\0010\0010\0010\0010\0010\0010\0010\0010\0010\001"
        ashun = <optimized out>
        res = 2
        sconf = <optimized out>
        chptr = <optimized out>
#3  0x00005555555f9085 in check_auth_finished (auth=auth@entry=0x5555568528b0) at s_auth.c:598
        flag = <optimized out>
        res = <optimized out>
        acptr = <optimized out>
        cptr = <optimized out>
#4  0x00005555555fc3f7 in iauth_parse (message=<optimized out>, iauth=0x5555567c6ab0) at s_auth.c:2536
        addr = {addr = {in6_16 = {49406, 306, 16896, 16896, 0, 0, 0, 5120}}, port = 40633}
        res = <optimized out>
        params = {0x5555557ee87c <readbuf+124> "25", 0x5555557ee87f <readbuf+127> "fec0:3201:42:42::14", 
          0x5555557ee893 <readbuf+147> "40633", 0x0, 0x555555623697 "ET_WRITE", 0x1 <error: Cannot access memory at address 0x1>, 
          0x5555556236a0 "ET_ACCEPT", 0x2 <error: Cannot access memory at address 0x2>, 0x5555556236aa "ET_CONNECT", 
          0x3 <error: Cannot access memory at address 0x3>, 0x5555556236b5 "ET_EOF", 0x4 <error: Cannot access memory at address 0x4>, 
          0x5555556236bc "ET_ERROR", 0x5 <error: Cannot access memory at address 0x5>, 0x5555556236c5 "ET_SIGNAL", 
          0x6 <error: Cannot access memory at address 0x6>}
        parc = <optimized out>
        auth = 0x5555568528b0
        has_cli = <optimized out>
        handler = <optimized out>
        cli = 0x55555660b240
        id = <optimized out>
        params = <optimized out>
        parc = <optimized out>
        handler = <optimized out>
        auth = <optimized out>
        cli = <optimized out>
        has_cli = <optimized out>
        id = <optimized out>
        addr = <optimized out>
        res = <optimized out>
#5  iauth_read (iauth=0x5555567c6ab0) at s_auth.c:2573
        length = <optimized out>
        count = 345
        sol = <optimized out>
        eol = 0x5555557ee899 <readbuf+153> ""
        readbuf = "> :Handling a hurry on 25\000\000> :Client 25 has Hurry set and 0 pending requests\000\000> :Passing client 25 (fec0:3201:4--Type <RET> for more, q to quit, c to continue without paging--
2:42::14)\000\000D 25\000fec0:3201:42:42::14\00040633\000\000> :Deleting client from hash tables\r\ns\r\nS iaut"...
        length = <optimized out>
        count = <optimized out>
        sol = <optimized out>
        eol = <optimized out>
#6  iauth_sock_callback (ev=<optimized out>) at s_auth.c:2601
        iauth = 0x5555567c6ab0
#7  0x00005555555b91f2 in event_execute (event=0x55555682e200) at ircd_events.c:162
No locals.
#8  event_generate (type=type@entry=ET_READ, arg=arg@entry=0x5555567c6ad8, data=data@entry=0) at ircd_events.c:414
        _ev = 0x55555682e200
        ptr = 0x55555682e200
        gen = 0x5555567c6ad8
#9  0x000055555561e6ac in engine_loop (gen=0x5555557e37a0 <evInfo>) at engine_epoll.c:333
        evt = 0x555556834d30
        sock = 0x5555567c6ad8
        codesize = 1432054403
        events_count = 200
        tmp = <optimized out>
        wait = <optimized out>
        errcode = 21845
        _gen = <optimized out>
#10 0x00005555555a2933 in main (argc=<optimized out>, argv=<optimized out>) at ircd.c:780
No locals.
(gdb) bt
#0  0x00007ffff7f0fb80 in SSL_get_version () from /lib/x86_64-linux-gnu/libssl.so.3
#1  0x00005555556130fc in ssl_get_cipher (ssl=0x0) at ssl.c:560
#2  0x000055555560baa7 in register_user (cptr=0x55555660b240, sptr=0x55555660b240) at s_user.c:455
#3  0x00005555555f9085 in check_auth_finished (auth=auth@entry=0x5555568528b0) at s_auth.c:598
#4  0x00005555555fc3f7 in iauth_parse (message=<optimized out>, iauth=0x5555567c6ab0) at s_auth.c:2536
#5  iauth_read (iauth=0x5555567c6ab0) at s_auth.c:2573
#6  iauth_sock_callback (ev=<optimized out>) at s_auth.c:2601
#7  0x00005555555b91f2 in event_execute (event=0x55555682e200) at ircd_events.c:162
#8  event_generate (type=type@entry=ET_READ, arg=arg@entry=0x5555567c6ad8, data=data@entry=0) at ircd_events.c:414
#9  0x000055555561e6ac in engine_loop (gen=0x5555557e37a0 <evInfo>) at engine_epoll.c:333
#10 0x00005555555a2933 in main (argc=<optimized out>, argv=<optimized out>) at ircd.c:780
(gdb) up
#1  0x00005555556130fc in ssl_get_cipher (ssl=0x0) at ssl.c:560
560	  strcpy(buf, SSL_get_version(ssl));
(gdb) up
#2  0x000055555560baa7 in register_user (cptr=0x55555660b240, sptr=0x55555660b240) at s_user.c:455
455	      sendcmdto_one(&me, CMD_NOTICE, sptr, "%C :You are connected to %s with %s", sptr,
(gdb) don
(gdb) down
#1  0x00005555556130fc in ssl_get_cipher (ssl=0x0) at ssl.c:560
560	  strcpy(buf, SSL_get_version(ssl));
(gdb) l
555	  static char buf[400];
556	  int bits;
557	  const SSL_CIPHER *c;
558	
559	  buf[0] = '\0';
560	  strcpy(buf, SSL_get_version(ssl));
561	  strcat(buf, "-");
562	  strcat(buf, SSL_get_cipher(ssl));
563	  c = SSL_get_current_cipher(ssl);
564	  SSL_CIPHER_get_bits(c, &bits);
(gdb) 
```

**Comment by jobe1986** [comment]
Fixed in commit 66526ec2e4143157c4daf4779441f2ce5a7230a3
